import Head from "next/head";
import Link from "next/link";
import styles from "./styles.module.css";
import _ from "lodash";

const HomeScreen = () => {
  // ============================================  RENDER
  return (
    <div className={styles.container}>
      <Head>
        <title>VB-CAPTCHA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="container is-fluid">
          <div className="tabs is-centered is-large is-fullwidth mb-6">
            <ul>
              <li className="is-active">
                <Link href="/">
                  <a>Home</a>
                </Link>
              </li>
              <li>
                <Link href="/signin">
                  <a>Sign In</a>
                </Link>
              </li>
              <li>
                <Link href="/train">
                  <a>Train</a>
                </Link>
              </li>
            </ul>
          </div>
          <h1 className={styles.title}>Welcome to VB-CAPTCHA</h1>
          <div className="columns my-6">
            <div className="column is-half is-flex is-justify-content-center">
              <Link href="/signin">
                <button className="button is-link is-light is-large">
                  Sign In
                </button>
                {/* <a>Sign In</a> */}
              </Link>
            </div>
            <div className="column is-half is-flex is-justify-content-center">
              <Link href="/train">
                <button className="button is-link is-light is-large">
                  Train
                </button>
              </Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

// ============================================  EXPORT
export default HomeScreen;
